name: CI/CD

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        working-directory: DZarsky.CommonLibraries

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x
      - name: Restore dependencies
        run: dotnet restore DZarsky.CommonLibraries.sln
      - name: Build
        run: dotnet build DZarsky.CommonLibraries.sln --configuration Release --no-restore
      - name: Setup NuGet.exe
        uses: NuGet/setup-nuget@v1.0.7
        with:
          nuget-version: latest
      - name: NuGet push
        run: nuget push **\*.nupkg -Source 'https://nuget.dzarsky.eu/' -ApiKey ${{secrets.NUGET_API_KEY}} -SkipDuplicate
        shell: pwsh
